In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sanikamal/rock-paper-scissors-dataset")

print("Path to dataset files:", path)

c:\Users\mehdi\anaconda3\envs\ACV\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 452M/452M [00:22<00:00, 21.0MB/s] 

Extracting files...


Path to dataset files: C:\Users\mehdi\.cache\kagglehub\datasets\sanikamal\rock-paper-scissors-dataset\versions\1


In [6]:
import cv2

cam = cv2.VideoCapture(0)

if not cam.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")

counter = 0
current_frame = None

def mouse_click(event, x, y, flags, param):
    global counter, current_frame
    if event == cv2.EVENT_LBUTTONDOWN:
        counter += 1
        filename = f"data/scissors/scissors{counter}.png"
        cv2.imwrite(filename, current_frame)
        print(f"Saved {filename}")

cv2.setMouseCallback("Camera", mouse_click)

while True:
    ret, frame = cam.read()
    if not ret:
        print("Failed to grab frame")
        break

    current_frame = frame.copy()
    cv2.imshow("Camera", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()


In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
Holistic = mp.solutions.holistic.Holistic

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)

In [8]:
import os
import pickle
dataset = []
target = []
folder_path_paper = "data/paper/" 
folder_path = folder_path_paper
all_files = os.listdir(folder_path)  # lists files and folders
files_only = [f for f in all_files if os.path.isfile(os.path.join(folder_path, f))]
counter = 0
L = len(files_only)
model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

for f in files_only:
    counter += 1
    print(100*counter/L,end="\r")
    image = plt.imread(folder_path+f)
    img_model = (image[..., :3] * 255).astype(np.uint8)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
    results = model.process(img_model)
    if results.pose_landmarks is not None:
        ldk = extract_landmarks(results.pose_landmarks.landmark)
        ldk_temp = extract_landmarks(results.pose_landmarks.landmark).flatten()
        dataset.append(ldk_temp)

with open(folder_path+'dataset_paper.pkl', 'wb') as file:  # 'wb' = write binary
    pickle.dump(dataset, file)

In [8]:
results.right_hand_landmarks

In [11]:
import os
import pickle
dataset = []
target = []
gestures = ["rock","paper","scissors"]
folder_path_rock = "data/rock/" 
folder_path_scissors = "data/scissors/" 
folder_paths = [folder_path_rock,folder_path_scissors]
# folder_path = folder_path_paper
for gesture in gestures:
    folder_path = "data/"+gesture+"/"
    all_files = os.listdir(folder_path)  # lists files and folders
    files_only = [f for f in all_files 
              if os.path.isfile(os.path.join(folder_path, f)) and f.lower().endswith('.png')]

    counter = 0
    L = len(files_only)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    for f in files_only:
        counter += 1
        print(100*counter/L,end="\r")
        image = plt.imread(folder_path+f)
        img_model = (image[..., :3] * 255).astype(np.uint8)
        model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
        results = model.process(img_model)
        if results.right_hand_landmarks is not None:
            ldk_temp = extract_landmarks(results.right_hand_landmarks.landmark).flatten()
            dataset.append(ldk_temp)

    with open(folder_path+'dataset_RightHand_'+gesture+'.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(dataset, file)

: 

In [10]:
results.right_hand_landmarks.landmark

[x: 0.122119345
y: 0.319025308
z: 1.1865135e-07
, x: 0.185522437
y: 0.284926057
z: -0.0177184865
, x: 0.226883456
y: 0.24733083
z: -0.0373208039
, x: 0.250067234
y: 0.229127049
z: -0.0579499565
, x: 0.273267329
y: 0.210052773
z: -0.0775989071
, x: 0.184952661
y: 0.124941185
z: -0.0293556582
, x: 0.23012042
y: 0.173848778
z: -0.0658163056
, x: 0.259506404
y: 0.221877158
z: -0.0943345129
, x: 0.28503406
y: 0.251581252
z: -0.112734973
, x: 0.144134387
y: 0.130193
z: -0.0384436101
, x: 0.209644854
y: 0.180779487
z: -0.0702716112
, x: 0.24725306
y: 0.223826885
z: -0.0855831578
, x: 0.277022541
y: 0.248032108
z: -0.0944473818
, x: 0.108671449
y: 0.16137746
z: -0.0503487922
, x: 0.174021378
y: 0.2359166
z: -0.0731117055
, x: 0.188233167
y: 0.268267453
z: -0.0731099695
, x: 0.193349153
y: 0.275238276
z: -0.0723286271
, x: 0.0837869644
y: 0.207059443
z: -0.0655160472
, x: 0.137967825
y: 0.271131545
z: -0.0778689533
, x: 0.152400494
y: 0.297455847
z: -0.074027136
, x: 0.1568432
y: 0.301144421
z:

### Loading Individual Datasets

In [6]:

import pickle
with open("data/paper/dataset_RightHand_paper.pkl", "rb") as f:
    paper = pickle.load(f)
with open("data/rock/dataset_RightHand_rock.pkl", "rb") as f:
    rock = pickle.load(f)
with open("data/scissors/dataset_RightHand_scissors.pkl", "rb") as f:
    scissors = pickle.load(f)

In [7]:
dataset = np.concatenate((np.array(rock),np.array(paper),np.array(scissors)),axis=0)
target = ['rock']*len(rock)+['paper']*len(paper)+['scissors']*len(scissors)
columns = []
for col in range(int(dataset.shape[1]/2)):
    columns.append(f"x{col}")
    columns.append(f"y{col}")


### Converting to DataFrame and Saving to Pickle

In [8]:
import pandas as pd
data = pd.DataFrame(data= dataset,columns=columns,index = range(len(dataset)))
data["target"] = target 
data.to_pickle("dataset_total_RightHand")

In [9]:
data

,x0,y0,x1,y1,x2,y2,x3,y3,x4,y4,...,y28,x29,y29,x30,y30,x31,y31,x32,y32,target
0,0.573672,0.226715,0.597984,0.182652,0.610599,0.183127,0.622673,0.184740,0.552199,0.183838,...,1.634890,0.647217,1.674711,0.437337,1.696116,0.617394,1.756058,0.475212,1.766375,rock
1,0.623997,0.223506,0.644071,0.179155,0.654671,0.180424,0.666460,0.182407,0.605887,0.174851,...,1.709306,0.648501,1.740728,0.440305,1.769788,0.634060,1.838012,0.470953,1.854074,rock
2,0.632985,0.219469,0.650398,0.175425,0.662927,0.178246,0.673683,0.181355,0.613584,0.169122,...,1.756562,0.642226,1.805191,0.433027,1.815429,0.629188,1.903030,0.459519,1.895632,rock
3,0.626983,0.228469,0.645842,0.185668,0.658333,0.188523,0.669365,0.191473,0.609351,0.178186,...,1.663587,0.633990,1.674600,0.443113,1.720998,0.628128,1.785809,0.459212,1.803824,rock
4,0.623410,0.230267,0.644129,0.187133,0.655855,0.188868,0.667474,0.191233,0.606050,0.182138,...,1.667756,0.648643,1.667208,0.439702,1.728901,0.652137,1.775167,0.454842,1.805939,rock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,0.469636,0.009649,0.492253,-0.026859,0.508277,-0.022540,0.523764,-0.017012,0.440335,-0.032687,...,0.765515,0.610249,0.875981,0.568586,0.779457,0.703506,0.888478,0.681577,0.790849,scissors
226,0.460862,0.012855,0.485094,-0.029270,0.500350,-0.026319,0.515269,-0.022566,0.433450,-0.034566,...,0.847279,0.585552,0.886532,0.599413,0.857025,0.594121,0.897126,0.716379,0.828488,scissors
227,0.476025,0.006265,0.502443,-0.038375,0.518714,-0.036131,0.535571,-0.032033,0.449544,-0.040124,...,0.952314,0.688379,1.092020,0.753143,0.989308,0.722057,1.091257,0.854979,0.954437,scissors
228,0.500015,0.002871,0.532573,-0.060429,0.549388,-0.055734,0.566298,-0.049260,0.478579,-0.070338,...,1.122086,0.608019,1.341848,0.625679,1.113417,0.670474,1.464290,0.733060,1.213806,scissors


## Neural Network Model

In [ ]:
landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
length_inputs = len(landmarks_of_interest)

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Dropout

# Create the model
model = Sequential([
    Input((2*length_inputs,)),
    Dense(128,activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')  # Output layer for 3 classes
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',  # Use for one-hot encoded labels
    metrics=['accuracy']
)

# Model summary
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         2,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,611 (49.26 KB)

 Trainable params: 12,611 (49.26 KB)

 Non-trainable params: 0 (0.00 B)

In [3]:
df = pd.read_pickle("dataset_total")
landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
length_inputs = len(landmarks_of_interest)
colOI = []
for col in landmarks_of_interest:
    colOI.append(col*2)
    colOI.append(col*2+1)
colOI.append(len(df.columns)-1)
sub_df = df[df.columns[colOI]]
from sklearn.model_selection import train_test_split
X = df[df.columns[colOI[:-1]]].values
y = df[df.columns[-1]].values
dummies = pd.get_dummies(y).astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, dummies, test_size=0.15, random_state=42)


In [21]:
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(
    monitor='val_loss',      # Metric to monitor
    patience=100,              # Stop after 5 epochs of no improvement
    verbose=1,               # Print messages when stopping
    restore_best_weights=True  # Restore model weights from the epoch with the best value of monitored metric
)


In [22]:
history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks = [early_stop]
)

Epoch 1/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.4217 - val_accuracy: 0.7451 - val_loss: 0.3657
Epoch 2/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7604 - loss: 0.4189 - val_accuracy: 0.7451 - val_loss: 0.3539
Epoch 3/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.4292 - val_accuracy: 0.7451 - val_loss: 0.3967
Epoch 4/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7465 - loss: 0.4383 - val_accuracy: 0.7255 - val_loss: 0.4006
Epoch 5/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7569 - loss: 0.4325 - val_accuracy: 0.7451 - val_loss: 0.3710
Epoch 6/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.4255 - val_accuracy: 0.7451 - val_loss: 0.3568
Epoch 7/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4567 - val_accuracy: 0.7451 - val_loss: 0.3497
Epoch 8/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7500 - loss: 0.4167 - val_accuracy: 0.7451 - val_loss: 0.3700

In [23]:
with open('model.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(model, file)

In [24]:
model.predict(X_test,verbose=0)

array([[3.76419594e-05, 5.89598145e-04, 9.99372780e-01],
       [9.97049928e-01, 8.57243489e-04, 2.09284481e-03],
       [9.96808112e-01, 8.17576190e-04, 2.37434334e-03],
       [2.44290868e-06, 4.49851364e-01, 5.50146222e-01],
       [9.99874830e-01, 3.23942550e-05, 9.27283472e-05],
       [2.34878229e-04, 4.25138026e-01, 5.74627042e-01],
       [1.12458020e-02, 3.12509865e-01, 6.76244318e-01],
       [1.84990946e-04, 3.42991110e-03, 9.96385098e-01],
       [1.44487258e-05, 3.60790896e-03, 9.96377647e-01],
       [7.27472529e-02, 3.99378330e-01, 5.27874470e-01],
       [7.70789444e-01, 9.64594260e-02, 1.32751182e-01],
       [3.19772516e-03, 3.80222410e-01, 6.16579890e-01],
       [1.43474003e-03, 8.94469582e-03, 9.89620447e-01],
       [9.99999285e-01, 1.14413929e-07, 5.65993957e-07],
       [9.97670829e-01, 8.00483220e-04, 1.52860093e-03],
       [7.57585000e-03, 4.31319326e-01, 5.61104834e-01],
       [9.95120704e-01, 1.80174073e-03, 3.07752588e-03],
       [1.84182602e-03, 3.89954

## RandomForest Model (66% Accuracy)

In [73]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
params = {'n_estimators': range(100,800,100),
          'max_depth' : range(2,5,2)}
cv = RandomizedSearchCV(rf,params,verbose=2,scoring="accuracy",n_jobs=-1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42)
history = cv.fit(X_train,y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [74]:
pd.DataFrame(history.cv_results_)


,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.195370,0.023129,0.088505,0.006555,600,4,"{'n_estimators': 600, 'max_depth': 4}",0.706897,0.603448,0.620690,0.684211,0.614035,0.645856,0.041572,8
1,0.192483,0.021954,0.012430,0.001859,100,2,"{'n_estimators': 100, 'max_depth': 2}",0.620690,0.637931,0.689655,0.596491,0.719298,0.652813,0.045173,3
2,1.524023,0.075228,0.093853,0.009314,700,2,"{'n_estimators': 700, 'max_depth': 2}",0.620690,0.672414,0.689655,0.561404,0.701754,0.649183,0.051882,5
3,0.840734,0.050709,0.052605,0.013381,400,2,"{'n_estimators': 400, 'max_depth': 2}",0.655172,0.655172,0.706897,0.561404,0.719298,0.659589,0.055646,2
4,0.231173,0.020247,0.013568,0.004035,100,4,"{'n_estimators': 100, 'max_depth': 4}",0.724138,0.603448,0.603448,0.684211,0.596491,0.642347,0.052099,9
5,0.932329,0.055516,0.056698,0.005751,400,4,"{'n_estimators': 400, 'max_depth': 4}",0.706897,0.637931,0.637931,0.684211,0.596491,0.652692,0.038797,4
6,1.126487,0.031704,0.067970,0.007856,500,4,"{'n_estimators': 500, 'max_depth': 4}",0.706897,0.603448,0.586207,0.684211,0.614035,0.638959,0.047599,10
7,0.980709,0.092516,0.066166,0.005243,500,2,"{'n_estimators': 500, 'max_depth': 2}",0.603448,0.689655,0.706897,0.578947,0.666667,0.649123,0.049597,7
8,0.417215,0.004333,0.028461,0.001564,200,2,"{'n_estimators': 200, 'max_depth': 2}",0.603448,0.672414,0.706897,0.561404,0.701754,0.649183,0.057326,5
9,0.986080,0.029130,0.052241,0.013281,600,2,"{'n_estimators': 600, 'max_depth': 2}",0.620690,0.689655,0.706897,0.596491,0.701754,0.663097,0.045503,1


## Training XgBoost Model (66% Accuracy)

In [77]:
ybis = y
ybis[ybis=='rock'] = 0 
ybis[ybis=='paper'] = 1 
ybis[ybis=='scissors'] = 2 
X_train, X_test, y_train, y_test = train_test_split(
    X, ybis, test_size=0.15, random_state=42)

In [78]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


model = xgb.XGBClassifier(
    objective='multi:softprob',  # probabilities for each class
    num_class=3,
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42
)
model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=True
)


[0]	validation_0-mlogloss:1.04243
[1]	validation_0-mlogloss:1.01166
[2]	validation_0-mlogloss:0.98542
[3]	validation_0-mlogloss:0.95266
[4]	validation_0-mlogloss:0.92429
[5]	validation_0-mlogloss:0.90269
[6]	validation_0-mlogloss:0.88242
[7]	validation_0-mlogloss:0.85825
[8]	validation_0-mlogloss:0.84342
[9]	validation_0-mlogloss:0.82595
[10]	validation_0-mlogloss:0.80786
[11]	validation_0-mlogloss:0.79072
[12]	validation_0-mlogloss:0.77851
[13]	validation_0-mlogloss:0.76497
[14]	validation_0-mlogloss:0.75371
[15]	validation_0-mlogloss:0.74318
[16]	validation_0-mlogloss:0.73348
[17]	validation_0-mlogloss:0.72282
[18]	validation_0-mlogloss:0.71443
[19]	validation_0-mlogloss:0.70671
[20]	validation_0-mlogloss:0.70088
[21]	validation_0-mlogloss:0.69352
[22]	validation_0-mlogloss:0.68341
[23]	validation_0-mlogloss:0.67402
[24]	validation_0-mlogloss:0.66635
[25]	validation_0-mlogloss:0.66120
[26]	validation_0-mlogloss:0.65694
[27]	validation_0-mlogloss:0.64872
[28]	validation_0-mlogloss:0.6

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softprob'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes fr

In [85]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
acc = accuracy_score(y_test.astype(int), y_pred)
print(f"Validation Accuracy: {acc:.4f}")


Validation Accuracy: 0.6667


## Live Test with Webcam

In [4]:
import cv2
import mediapipe as mp
import pickle
import cv2
import mediapipe as mp
import pickle
import numpy as np   # <--- add this

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
drawing_utils = mp.solutions.drawing_utils
drawing_styles = mp.solutions.drawing_styles
gesture = ['paper', 'rock', 'scissors','None']

cap = cv2.VideoCapture(0)  # Open webcam

if not cap.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")
with open("model.pkl", "rb") as f:
    model = pickle.load(f)
ind = 3 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Flip for a mirror view
        frame = cv2.flip(frame, 1)
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make predictions
        results = holistic.process(rgb_frame)
        if results.pose_landmarks is not None:
            features = extract_landmarks(results.pose_landmarks.landmark).reshape(1, -1)
            sample = features[0:1, colOI[:-1]]   # already (1, n_features)
            # Predict using the pre-trained ML model
            prediction = model.predict(sample,verbose=0)
            if (prediction>.85).any():
                ind = np.argmax(prediction)
                print(prediction)
            else:
                ind = 3
         
        drawing_utils.draw_landmarks(
            frame,
            results.left_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )

        drawing_utils.draw_landmarks(
            frame,
            results.right_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )
        # # Display prediction
        cv2.putText(frame, f'Gesture Detected: {gesture[ind]}', (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        cv2.imshow("Camera", frame)

        if cv2.waitKey(1) & 0xFF == 27:  # ESC to quit
            break

cap.release()
cv2.destroyAllWindows()


[[0.9620116  0.0135947  0.02439377]]
[[0.9787775  0.00758281 0.01363975]]
[[0.98276097 0.00613048 0.01110859]]
[[0.9841031  0.00563335 0.01026362]]
[[0.97947663 0.00745435 0.01306905]]
[[0.97709376 0.00847818 0.01442812]]
[[0.98479307 0.00550348 0.00970353]]
[[0.98425746 0.00569497 0.01004756]]
[[0.9874814  0.00446309 0.00805545]]
[[0.98878163 0.00394221 0.00727617]]
[[0.9875896  0.00437366 0.00803674]]
[[0.9874255  0.00443482 0.00813964]]
[[0.98994714 0.00351607 0.00653686]]
[[0.9905087  0.00329041 0.00620095]]
[[0.99572337 0.00137617 0.00290039]]
[[0.99661034 0.00120622 0.00218337]]
[[9.9990129e-01 2.6088555e-05 7.2603456e-05]]
[[9.9997640e-01 5.6097524e-06 1.8051342e-05]]
[[9.9997747e-01 5.4195825e-06 1.7141238e-05]]
[[9.9997079e-01 7.2502876e-06 2.1900009e-05]]
[[9.9997389e-01 6.4445135e-06 1.9631458e-05]]
[[9.9999380e-01 1.2635031e-06 4.8577963e-06]]
[[9.9999321e-01 1.4253612e-06 5.3983426e-06]]
[[9.9998951e-01 2.3219227e-06 8.2708830e-06]]
[[9.9999464e-01 1.0911922e-06 4.2999686e

mediapipe.python.solution_base.SolutionOutputs