In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sanikamal/rock-paper-scissors-dataset")

print("Path to dataset files:", path)

c:\Users\mehdi\anaconda3\envs\ACV\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 452M/452M [00:22<00:00, 21.0MB/s] 

Extracting files...


Path to dataset files: C:\Users\mehdi\.cache\kagglehub\datasets\sanikamal\rock-paper-scissors-dataset\versions\1


In [ ]:
import cv2

cam = cv2.VideoCapture(0)

if not cam.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")

counter = 0
current_frame = None

def mouse_click(event, x, y, flags, param):
    global counter, current_frame
    if event == cv2.EVENT_LBUTTONDOWN:
        counter += 1
        filename = f"data/scissors/scissors{counter}.png"
        cv2.imwrite(filename, current_frame)
        print(f"Saved {filename}")

cv2.setMouseCallback("Camera", mouse_click)

while True:
    ret, frame = cam.read()
    if not ret:
        print("Failed to grab frame")
        break

    current_frame = frame.copy()
    # current_frame = cv2.flip(current_frame, 1)
    # rgb_frame = cv2.cvtColor(current_frame, cv2.COLOR_BGR2RGB)
    # results = holistic.process(rgb_frame)
        # Make predictions
        
    cv2.imshow("Camera", frame)
    # drawing_utils.draw_landmarks(
    #         frame,
    #         results.right_hand_landmarks,
    #         mp.solutions.holistic.HAND_CONNECTIONS,
    #         connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
    #     )
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()


ValueError: _graph is None in SolutionBase

: 

In [2]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
Holistic = mp.solutions.holistic.Holistic

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)

In [8]:
import os
import pickle
dataset = []
target = []
folder_path_paper = "data/paper/" 
folder_path = folder_path_paper
all_files = os.listdir(folder_path)  # lists files and folders
files_only = [f for f in all_files if os.path.isfile(os.path.join(folder_path, f))]
counter = 0
L = len(files_only)
model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

for f in files_only:
    counter += 1
    print(100*counter/L,end="\r")
    image = plt.imread(folder_path+f)
    img_model = (image[..., :3] * 255).astype(np.uint8)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
    results = model.process(img_model)
    if results.pose_landmarks is not None:
        ldk = extract_landmarks(results.pose_landmarks.landmark)
        ldk_temp = extract_landmarks(results.pose_landmarks.landmark).flatten()
        dataset.append(ldk_temp)

with open(folder_path+'dataset_paper.pkl', 'wb') as file:  # 'wb' = write binary
    pickle.dump(dataset, file)

In [44]:
import os
import pickle
dataset = []
target = []
gestures = ["rock","paper","scissors"]
folder_path_rock = "data/rock/" 
folder_path_scissors = "data/scissors/" 
folder_paths = [folder_path_rock,folder_path_scissors]
# folder_path = folder_path_paper
for gesture in gestures:
    folder_path = "data/"+gesture+"/"
    all_files = os.listdir(folder_path)  # lists files and folders
    files_only = [f for f in all_files 
              if os.path.isfile(os.path.join(folder_path, f)) and f.lower().endswith('.png')]

    for f in files_only:
        print(f)

paper_10001.png
paper_10002.png
paper_10003.png
paper_10004.png
paper_10005.png
paper_10006.png
paper_10007.png
paper_10008.png
paper_10009.png
paper_10010.png
paper_10011.png
paper_10012.png
paper_10013.png
paper_10014.png
paper_10015.png
paper_10016.png
paper_10017.png
paper_10018.png
paper_10019.png
paper_10020.png
paper_10021.png
paper_10022.png
paper_10023.png
paper_10024.png
paper_10025.png
paper_10026.png
paper_10027.png
paper_10028.png
paper_10029.png
paper_10030.png
paper_10031.png
paper_10032.png
paper_10033.png
paper_10034.png
paper_10035.png
paper_10036.png
paper_10037.png
paper_10038.png
paper_10039.png
paper_10040.png
paper_10041.png
paper_10042.png
paper_10043.png
paper_10044.png
paper_10045.png
paper_10046.png
paper_10047.png
paper_10048.png
paper_10049.png
paper_10050.png
paper_10051.png
paper_10052.png
paper_10053.png
paper_10054.png
paper_10055.png
paper_10056.png
paper_10057.png
paper_10058.png
paper_10059.png
paper_10060.png
paper_10061.png
paper_10062.png
paper_10

In [11]:
import os
import pickle
dataset = []
target = []
gestures = ["rock","paper","scissors"]
folder_path_rock = "data/rock/" 
folder_path_scissors = "data/scissors/" 
folder_paths = [folder_path_rock,folder_path_scissors]
# folder_path = folder_path_paper
for gesture in gestures:
    folder_path = "data/"+gesture+"/"
    all_files = os.listdir(folder_path)  # lists files and folders
    files_only = [f for f in all_files 
              if os.path.isfile(os.path.join(folder_path, f)) and f.lower().endswith('.png')]

    counter = 0
    L = len(files_only)
    model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    for f in files_only:
        counter += 1
        print(100*counter/L,end="\r")
        image = plt.imread(folder_path+f)
        img_model = (image[..., :3] * 255).astype(np.uint8)
        model = Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5)
        results = model.process(img_model)
        if results.right_hand_landmarks is not None:
            ldk_temp = extract_landmarks(results.right_hand_landmarks.landmark).flatten()
            dataset.append(ldk_temp)

    with open(folder_path+'dataset_RightHand_'+gesture+'.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(dataset, file)

: 

### Loading Individual Datasets

In [3]:

import pickle
import numpy as np 
with open("data/paper/dataset_RightHand_paper.pkl", "rb") as f:
    paper = pickle.load(f)
with open("data/rock/dataset_RightHand_rock.pkl", "rb") as f:
    rock = pickle.load(f)
with open("data/scissors/dataset_RightHand_scissors.pkl", "rb") as f:
    scissors = pickle.load(f)

with open("data/paper/Manual_dataset_RightHand_paper.pkl", "rb") as f:
    paper = pickle.load(f)
with open("data/rock/Manual_dataset_RightHand_rock.pkl", "rb") as f:
    rock = pickle.load(f)
with open("data/scissors/Manual_dataset_RightHand_scissors.pkl", "rb") as f:
    scissors = pickle.load(f)

In [33]:
frame.shape
np.array(rock)[4,:]

array([0.48512995, 0.7842816 , 0.5057544 , 0.7211495 , 0.5522447 ,
       0.6790783 , 0.5971153 , 0.67340624, 0.6289398 , 0.6971918 ,
       0.5448042 , 0.72121245, 0.62449414, 0.72922736, 0.6279619 ,
       0.72163785, 0.60983187, 0.7211912 , 0.5443914 , 0.7748249 ,
       0.63122046, 0.7777645 , 0.6349659 , 0.76188916, 0.616212  ,
       0.75723475, 0.5476186 , 0.8185406 , 0.6271627 , 0.8222489 ,
       0.62924755, 0.80254525, 0.6124329 , 0.7924961 , 0.55048317,
       0.85129166, 0.61332965, 0.85229   , 0.61828464, 0.8343419 ,
       0.60487753, 0.8238002 ], dtype=float32)

In [42]:
import cv2
import numpy as np
import mediapipe as mp
from mediapipe.framework.formats import landmark_pb2

# Initialize Mediapipe drawing utils
mp_holistic = mp.solutions.holistic
drawing_utils = mp.solutions.drawing_utils
drawing_styles = mp.solutions.drawing_styles

# Load the image
frame = cv2.imread("data/paper/paper_10.png")
frame = cv2.flip(frame, 1)
h, w, _ = frame.shape

# Example: rock[4,:] = [x0, y0, x1, y1, ...] in normalized coordinates (0-1)
landmark_array = np.array(paper)[10, :]  # 1D array: x0,y0,x1,y1,...
num_landmarks = len(landmark_array)//2

# Convert to Mediapipe landmarks
mp_landmarks = landmark_pb2.NormalizedLandmarkList(
    landmark=[
        landmark_pb2.NormalizedLandmark(
            x=landmark_array[i*2],       # x in [0,1]
            y=landmark_array[i*2 + 1],   # y in [0,1]
            z=0
        ) for i in range(num_landmarks)
    ]
)

# Draw landmarks
drawing_utils.draw_landmarks(
    frame,
    mp_landmarks,
    mp_holistic.HAND_CONNECTIONS,
    connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
)

# Display image
cv2.imshow("Right Hand Landmarks", frame)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [4]:
dataset = np.concatenate((np.array(rock),np.array(paper),np.array(scissors)),axis=0)
target = ['rock']*len(rock)+['paper']*len(paper)+['scissors']*len(scissors)
columns = []
for col in range(int(dataset.shape[1]/2)):
    columns.append(f"x{col}")
    columns.append(f"y{col}")


### Converting to DataFrame and Saving to Pickle

In [5]:
import pandas as pd
data = pd.DataFrame(data= dataset,columns=columns,index = range(len(dataset)))
data["target"] = target 
data.to_pickle("Manual_dataset_total_RightHand")

In [6]:
data

,x0,y0,x1,y1,x2,y2,x3,y3,x4,y4,...,y16,x17,y17,x18,y18,x19,y19,x20,y20,target
0,0.354044,0.702669,0.366195,0.604117,0.393771,0.519150,0.415509,0.475797,0.439035,0.494201,...,0.669451,0.404685,0.750734,0.494555,0.718757,0.489884,0.709835,0.465817,0.704697,rock
1,0.346642,0.587548,0.390175,0.541333,0.447471,0.536898,0.486748,0.560452,0.511653,0.583488,...,0.658814,0.417486,0.630905,0.455076,0.654996,0.474655,0.671155,0.488791,0.680362,rock
2,0.328289,0.530215,0.380906,0.521256,0.424434,0.487091,0.447218,0.448615,0.452064,0.408969,...,0.468529,0.314970,0.379803,0.328700,0.423287,0.330438,0.461428,0.330168,0.466057,rock
3,0.342776,0.473864,0.355746,0.538736,0.393720,0.584570,0.433836,0.606253,0.467084,0.604849,...,0.488927,0.435523,0.442849,0.451469,0.460590,0.422534,0.466527,0.411900,0.461942,rock
4,0.309136,0.562808,0.316448,0.501937,0.345776,0.443173,0.379398,0.416380,0.408780,0.427994,...,0.539501,0.362336,0.598569,0.416849,0.575756,0.403405,0.571115,0.382378,0.574364,rock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,0.313877,0.757314,0.315646,0.733705,0.293622,0.717647,0.264359,0.724730,0.236345,0.726603,...,0.749157,0.237609,0.720295,0.225157,0.741939,0.245839,0.756184,0.263857,0.758030,scissors
286,0.323123,0.768068,0.346497,0.736670,0.352317,0.687726,0.337198,0.658643,0.311631,0.651415,...,0.717226,0.265713,0.689669,0.279442,0.683937,0.298947,0.707137,0.310715,0.726091,scissors
287,0.347847,0.742532,0.363908,0.688740,0.397680,0.659026,0.430369,0.662071,0.453300,0.671557,...,0.698230,0.409688,0.738370,0.450217,0.727421,0.441865,0.721416,0.427869,0.717916,scissors
288,0.330955,0.746068,0.362327,0.703578,0.406857,0.702167,0.440762,0.723368,0.460617,0.739639,...,0.765729,0.394701,0.803210,0.439125,0.791890,0.432787,0.774893,0.419290,0.769035,scissors


## Neural Network Model

In [7]:
landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
landmarks_of_interest = range(int((data.shape[1]-1)/2))
length_inputs = len(landmarks_of_interest)

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Dropout

# Create the model
model = Sequential([
    Input((2*length_inputs,)),
    Dense(128,activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    # Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')  # Output layer for 3 classes
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',  # Use for one-hot encoded labels
    metrics=['accuracy']
)

# Model summary
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         5,504 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,939 (62.26 KB)

 Trainable params: 15,939 (62.26 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
df = pd.read_pickle("Manual_dataset_total_RightHand")
# landmarks_of_interest = [15,16,17,18,19,20,21,22] # Right and Left Hanhs Landmarks
# length_inputs = len(landmarks_of_interest)
# colOI = []
# for col in landmarks_of_interest:
#     colOI.append(col*2)
#     colOI.append(col*2+1)
# colOI.append(len(df.columns)-1)
# sub_df = df[df.columns[colOI]]


from sklearn.model_selection import train_test_split
X = df[df.columns[:-1]].values
y = df[df.columns[-1]].values
dummies = pd.get_dummies(y).astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, dummies, test_size=0.15, random_state=42)


In [15]:
y_train

,paper,rock,scissors
180,1,0,0
30,0,1,0
22,0,1,0
24,0,1,0
225,0,0,1
...,...,...,...
188,0,0,1
71,0,1,0
106,1,0,0
270,0,0,1


In [17]:
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(
    monitor='val_loss',      # Metric to monitor
    patience=100,              # Stop after 5 epochs of no improvement
    verbose=1,               # Print messages when stopping
    restore_best_weights=True  # Restore model weights from the epoch with the best value of monitored metric
)


In [18]:
history = model.fit(
    X_train,
    y_train.values,
    epochs=200,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks = [early_stop]
)

Epoch 1/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.3618 - loss: 1.1349 - val_accuracy: 0.4545 - val_loss: 1.0741
Epoch 2/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4024 - loss: 1.0650 - val_accuracy: 0.4318 - val_loss: 1.0858
Epoch 3/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4431 - loss: 1.0340 - val_accuracy: 0.4318 - val_loss: 1.0675
Epoch 4/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4715 - loss: 1.0140 - val_accuracy: 0.4318 - val_loss: 1.0603
Epoch 5/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4756 - loss: 0.9729 - val_accuracy: 0.5227 - val_loss: 1.0358
Epoch 6/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5366 - loss: 0.9244 - val_accuracy: 0.5000 - val_loss: 1.0246
Epoch 7/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5163 - loss: 0.9280 - val_accuracy: 0.4773 - val_loss: 0.9910
Epoch 8/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5528 - loss: 0.8825 - val_accuracy: 0.5455 - val_loss: 0.9

In [20]:
with open('model.pkl', 'wb') as file:  # 'wb' = write binary
        pickle.dump(model, file)

## RandomForest Model (66% Accuracy)

In [13]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
params = {'n_estimators': range(100,800,100),
          'max_depth' : range(2,5,2)}
cv = RandomizedSearchCV(rf,params,verbose=2,scoring="accuracy",n_jobs=-1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42)
history = cv.fit(X_train,y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [74]:
pd.DataFrame(history.cv_results_)


,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.195370,0.023129,0.088505,0.006555,600,4,"{'n_estimators': 600, 'max_depth': 4}",0.706897,0.603448,0.620690,0.684211,0.614035,0.645856,0.041572,8
1,0.192483,0.021954,0.012430,0.001859,100,2,"{'n_estimators': 100, 'max_depth': 2}",0.620690,0.637931,0.689655,0.596491,0.719298,0.652813,0.045173,3
2,1.524023,0.075228,0.093853,0.009314,700,2,"{'n_estimators': 700, 'max_depth': 2}",0.620690,0.672414,0.689655,0.561404,0.701754,0.649183,0.051882,5
3,0.840734,0.050709,0.052605,0.013381,400,2,"{'n_estimators': 400, 'max_depth': 2}",0.655172,0.655172,0.706897,0.561404,0.719298,0.659589,0.055646,2
4,0.231173,0.020247,0.013568,0.004035,100,4,"{'n_estimators': 100, 'max_depth': 4}",0.724138,0.603448,0.603448,0.684211,0.596491,0.642347,0.052099,9
5,0.932329,0.055516,0.056698,0.005751,400,4,"{'n_estimators': 400, 'max_depth': 4}",0.706897,0.637931,0.637931,0.684211,0.596491,0.652692,0.038797,4
6,1.126487,0.031704,0.067970,0.007856,500,4,"{'n_estimators': 500, 'max_depth': 4}",0.706897,0.603448,0.586207,0.684211,0.614035,0.638959,0.047599,10
7,0.980709,0.092516,0.066166,0.005243,500,2,"{'n_estimators': 500, 'max_depth': 2}",0.603448,0.689655,0.706897,0.578947,0.666667,0.649123,0.049597,7
8,0.417215,0.004333,0.028461,0.001564,200,2,"{'n_estimators': 200, 'max_depth': 2}",0.603448,0.672414,0.706897,0.561404,0.701754,0.649183,0.057326,5
9,0.986080,0.029130,0.052241,0.013281,600,2,"{'n_estimators': 600, 'max_depth': 2}",0.620690,0.689655,0.706897,0.596491,0.701754,0.663097,0.045503,1


## Training XgBoost Model (66% Accuracy)

In [77]:
ybis = y
ybis[ybis=='rock'] = 0 
ybis[ybis=='paper'] = 1 
ybis[ybis=='scissors'] = 2 
X_train, X_test, y_train, y_test = train_test_split(
    X, ybis, test_size=0.15, random_state=42)

In [78]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


model = xgb.XGBClassifier(
    objective='multi:softprob',  # probabilities for each class
    num_class=3,
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42
)
model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=True
)


[0]	validation_0-mlogloss:1.04243
[1]	validation_0-mlogloss:1.01166
[2]	validation_0-mlogloss:0.98542
[3]	validation_0-mlogloss:0.95266
[4]	validation_0-mlogloss:0.92429
[5]	validation_0-mlogloss:0.90269
[6]	validation_0-mlogloss:0.88242
[7]	validation_0-mlogloss:0.85825
[8]	validation_0-mlogloss:0.84342
[9]	validation_0-mlogloss:0.82595
[10]	validation_0-mlogloss:0.80786
[11]	validation_0-mlogloss:0.79072
[12]	validation_0-mlogloss:0.77851
[13]	validation_0-mlogloss:0.76497
[14]	validation_0-mlogloss:0.75371
[15]	validation_0-mlogloss:0.74318
[16]	validation_0-mlogloss:0.73348
[17]	validation_0-mlogloss:0.72282
[18]	validation_0-mlogloss:0.71443
[19]	validation_0-mlogloss:0.70671
[20]	validation_0-mlogloss:0.70088
[21]	validation_0-mlogloss:0.69352
[22]	validation_0-mlogloss:0.68341
[23]	validation_0-mlogloss:0.67402
[24]	validation_0-mlogloss:0.66635
[25]	validation_0-mlogloss:0.66120
[26]	validation_0-mlogloss:0.65694
[27]	validation_0-mlogloss:0.64872
[28]	validation_0-mlogloss:0.6

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softprob'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes fr

In [85]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
acc = accuracy_score(y_test.astype(int), y_pred)
print(f"Validation Accuracy: {acc:.4f}")


Validation Accuracy: 0.6667


## Live Test with Webcam

In [3]:
import cv2
import mediapipe as mp
import pickle
import cv2
import mediapipe as mp
import pickle
import numpy as np   # <--- add this

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
drawing_utils = mp.solutions.drawing_utils
drawing_styles = mp.solutions.drawing_styles
gesture = ['paper', 'rock', 'scissors','None']

cap = cv2.VideoCapture(0)  # Open webcam

if not cap.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")
with open("model.pkl", "rb") as f:
    model = pickle.load(f)
ind = 3 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Flip for a mirror view
        # frame = cv2.flip(frame, 1)
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make predictions
        results = holistic.process(rgb_frame)
        if results.right_hand_landmarks is not None:
            features = extract_landmarks(results.right_hand_landmarks.landmark).reshape(1, -1)
            sample = features[:, :]   # already (1, n_features)
            # Predict using the pre-trained ML model
            prediction = model.predict(sample,verbose=0)
            if (prediction>.85).any():
                ind = np.argmax(prediction)
                print(prediction)
            else:
                ind = 3
         
        drawing_utils.draw_landmarks(
            frame,
            results.left_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )

        drawing_utils.draw_landmarks(
            frame,
            results.right_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )
        # # Display prediction
        cv2.putText(frame, f'Gesture Detected: {gesture[ind]}', (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        cv2.imshow("Camera", frame)

        if cv2.waitKey(1) & 0xFF == 27:  # ESC to quit
            break

cap.release()
cv2.destroyAllWindows()


[[1.0513113e-05 4.4277263e-07 9.9998903e-01]]
[[4.5147019e-05 7.9533957e-06 9.9994683e-01]]
[[5.8136513e-05 1.2014047e-05 9.9992979e-01]]
[[5.8616166e-05 1.2791737e-05 9.9992859e-01]]
[[7.8858400e-05 1.9166977e-05 9.9990189e-01]]
[[8.2152721e-05 2.1584176e-05 9.9989629e-01]]
[[9.2393806e-05 3.2495474e-05 9.9987507e-01]]
[[8.0501297e-05 2.9089562e-05 9.9989045e-01]]
[[8.171515e-05 2.669747e-05 9.998915e-01]]
[[7.3897376e-05 2.2985227e-05 9.9990308e-01]]
[[6.913027e-05 2.198671e-05 9.999089e-01]]
[[7.2099661e-05 2.1160866e-05 9.9990666e-01]]
[[7.4156684e-05 3.2128424e-05 9.9989367e-01]]
[[1.1811679e-04 1.2900468e-04 9.9975294e-01]]
[[1.9418371e-04 2.7014818e-03 9.9710435e-01]]
[[0.00349962 0.10247158 0.89402884]]
[[0.9626841  0.00453524 0.03278064]]
[[0.95417833 0.00289419 0.04292757]]
[[0.9766509  0.00166502 0.02168408]]
[[1.3805610e-01 7.1565295e-04 8.6122817e-01]]
[[1.24559276e-01 6.48839341e-04 8.74791920e-01]]
[[1.2563358e-01 5.9813529e-04 8.7376839e-01]]
[[1.040455e-01 5.136910e-04

In [ ]:
import cv2
import mediapipe as mp
import pickle
import cv2
import mediapipe as mp
import pickle
import numpy as np   # <--- add this

def extract_landmarks(landmarks):
    return np.array([[l.x, l.y] for l in landmarks],dtype=np.float32)
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils
drawing_utils = mp.solutions.drawing_utils
drawing_styles = mp.solutions.drawing_styles
gesture = ['paper', 'rock', 'scissors','None']

cap = cv2.VideoCapture(0)  # Open webcam

if not cap.isOpened():
    print("Error: Camera not opened")
    exit()

cv2.namedWindow("Camera")
with open("model.pkl", "rb") as f:
    model = pickle.load(f)
counter = 0 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    def mouse_click(event, x, y, flags, param):
        global counter, current_frame
        if event == cv2.EVENT_LBUTTONDOWN:
             counter+=1
             if results is not None:
                ldk_temp = extract_landmarks(results)
                dataset.append(ldk_temp)
                # Save updated dataset
                with open(dataset_file, "wb") as f:
                    pickle.dump(dataset, f)
                print(f"Updated dataset with {len(ldk_temp)} landmarks.")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Flip for a mirror view
        frame = cv2.flip(frame, 1)
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make predictions
        results = holistic.process(rgb_frame)
        cv2.setMouseCallback("Camera", mouse_click,param=results.right_hand_landmarks.landmark)

         
        

        drawing_utils.draw_landmarks(
            frame,
            results.right_hand_landmarks,
            mp.solutions.holistic.HAND_CONNECTIONS,
            connection_drawing_spec=drawing_styles.get_default_hand_connections_style()
        )
        

        cv2.imshow("Camera", frame)

        if cv2.waitKey(1) & 0xFF == 27:  # ESC to quit
            break

cap.release()
cv2.destroyAllWindows()



mediapipe.python.solution_base.SolutionOutputs

In [2]:
import cv2
import pickle
import numpy as np
import mediapipe as mp

Holistic = mp.solutions.holistic.Holistic

# Globals
counter = 0
current_frame = None
dataset_file = "data/rock/Manual_dataset_RightHand_rock.pkl"

# Load existing dataset or create empty list
try:
    with open(dataset_file, "rb") as f:
        dataset = pickle.load(f)
except FileNotFoundError:
    dataset = []

def extract_landmarks(landmarks):
    # Access the .landmark attribute which is a list
    return np.array([[l.x, l.y] for l in landmarks.landmark], dtype=np.float32).flatten()

# Mouse callback
def mouse_click(event, x, y, flags, param):
    global counter, current_frame, dataset
    results = param  # param is right_hand_landmarks
    if event == cv2.EVENT_LBUTTONDOWN:
        if current_frame is not None:
            counter += 1
           
            print(counter)

            # Append landmarks if available
            if results is not None:
                ldk_temp = extract_landmarks(results)
                dataset.append(ldk_temp)
                # Save updated dataset
                with open(dataset_file, "wb") as f:
                    pickle.dump(dataset, f)
                print(f"Updated dataset with {len(ldk_temp)} landmarks.")

# Initialize webcam and Mediapipe
cap = cv2.VideoCapture(0)
cv2.namedWindow("Camera")

with Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as mp_holistic:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # frame = cv2.flip(frame, 1)
        current_frame = frame.copy()  # store for saving
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        results = mp_holistic.process(rgb_frame)
        # Pass right_hand_landmarks to mouse callback
        cv2.setMouseCallback("Camera", mouse_click, param=results.right_hand_landmarks)

        # Draw landmarks for visualization
        if results.right_hand_landmarks:
            mp.solutions.drawing_utils.draw_landmarks(
                frame,
                results.right_hand_landmarks,
                mp.solutions.holistic.HAND_CONNECTIONS
            )

        cv2.imshow("Camera", frame)
        if cv2.waitKey(1) & 0xFF == 27:  # ESC to quit
            break

cap.release()
cv2.destroyAllWindows()


AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

1
Updated dataset with 42 landmarks.
2
Updated dataset with 42 landmarks.
3
Updated dataset with 42 landmarks.
4
Updated dataset with 42 landmarks.
5
Updated dataset with 42 landmarks.
6
Updated dataset with 42 landmarks.
7
Updated dataset with 42 landmarks.
8
Updated dataset with 42 landmarks.
9
Updated dataset with 42 landmarks.
10
Updated dataset with 42 landmarks.
11
Updated dataset with 42 landmarks.
12
Updated dataset with 42 landmarks.
13
Updated dataset with 42 landmarks.
14
Updated dataset with 42 landmarks.
15
Updated dataset with 42 landmarks.
16
Updated dataset with 42 landmarks.
17
Updated dataset with 42 landmarks.
18
Updated dataset with 42 landmarks.
19
Updated dataset with 42 landmarks.
20
Updated dataset with 42 landmarks.
21
Updated dataset with 42 landmarks.
22
Updated dataset with 42 landmarks.
23
Updated dataset with 42 landmarks.
24
Updated dataset with 42 landmarks.
25
Updated dataset with 42 landmarks.
26
Updated dataset with 42 landmarks.
27
Updated dataset wi

In [8]:
with open("data/scissors/Manual_dataset_RightHand_scissors.pkl", "rb") as f:
    ds = pickle.load(f)

In [10]:
np.array(ds).shape

(13, 42)